# Конфигурация плагина DDReports

# Сообщения, которые будут отображаться игрокам и модераторам
messages:
  report-submitted: "Вы подали жалобу на игрока %target% по причине: %reason%."
  report-received: "Новая жалоба от игрока %player% на %target%: %reason%."
  no-permission: "У вас нет прав для выполнения этой команды."
  incorrect-usage: "Использование команды неверное! Используйте: %usage%"
  player-not-found: "Игрок с таким именем не найден."
  no-reports: "Нет доступных жалоб."
  report-list: "Список всех жалоб:"
  report-entry: "Жалоба: %report%"
  report-cleared: "Все репорты были очищены."
  report-count: "Всего жалоб: %count%."
