cooldown:
  time: 60 # время в секундах

messages:
  cooldown: "&cПодождите %time% секунд перед отправкой следующей жалобы"
  incorrect-usage: "&cИспользование: %usage%"
  player-not-found: "&cИгрок не найден!"
  report-submitted: "&aЖалоба на игрока %target% отправлена! Причина: %reason%"
  report-received: "&c%player% &7отправил жалобу на &c%target% &7по причине: &f%reason%"
  no-permission: "&cУ вас нет прав!"
  report-cleared: "&aВсе жалобы очищены!"
  no-reports: "&cНет активных жалоб!"
  report-list: "&7Список жалоб:"
  report-entry: "%report%"