name: DDReports
version: '1.1'
main: lunadev.ddreports.DDReports
api-version: '1.16'
commands:
  report:
    description: Подать жалобу на игрока
    usage: /report <игрок> <причина>
  reports:
    description: Просмотр списка жалоб
    usage: /reports [clear]
permissions:
  ddreports.view:
    description: Позволяет просматривать жалобы
    default: op
  ddreports.manage:
    description: Позволяет управлять жалобами
    default: op